// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCCS5BMUjZXHQT3uNOI6Xg21SUZjPeshFo',
    appId: '1:580862904979:web:b28851a1582845594bdb66',
    messagingSenderId: '580862904979',
    projectId: 'my-final-project-da35b',
    authDomain: 'my-final-project-da35b.firebaseapp.com',
    storageBucket: 'my-final-project-da35b.firebasestorage.app',
    measurementId: 'G-WD2D5KG3R6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB0TMdrRXJ24IJ1ZqUEeo6OMht1CY35EPg',
    appId: '1:580862904979:android:a4456cc390ef078c4bdb66',
    messagingSenderId: '580862904979',
    projectId: 'my-final-project-da35b',
    storageBucket: 'my-final-project-da35b.firebasestorage.app',
  );
}
